n1=str(input("introduceti primul cuv :"))
n2=str(input("introduceti al doilea cuv :"))
n3=str(input("introduceti al treilea cuv :"))
n4=str(input("introduceti al patrulea cuv :"))
print(n1)
print(n2)
print(n3)
print(n4)
print(n1 +" "+ n2 +" "+ n3 +" "+ n4 +".")